# Generated by Django 4.0 on 2022-01-08 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.IntegerField(primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=30)),
                ('system_ip', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=30)),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.node')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_id_str', models.IntegerField()),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.node')),
            ],
        ),
        migrations.CreateModel(
            name='SdpBinding',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_id_str', models.IntegerField()),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='Sdp',
            fields=[
                ('sdp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.node')),
            ],
        ),
        migrations.CreateModel(
            name='Sap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outer_vlan', models.IntegerField()),
                ('inner_vlan', models.IntegerField()),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.node')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.port')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
