# Generated by Django 4.0 on 2022-01-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdp',
            name='node_id',
        ),
        migrations.AddField(
            model_name='sdp',
            name='from_node',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='from_node_id', to='services.node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sdp',
            name='to_node',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='to_node_id', to='services.node'),
            preserve_default=False,
        ),
    ]
