# Generated by Django 4.0 on 2022-01-10 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_sdp_node_id_sdp_from_node_sdp_to_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='node_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='sdp',
            old_name='sdp_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='sdpbinding',
            old_name='service_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='sap',
            name='node_id',
        ),
        migrations.RemoveField(
            model_name='sdpbinding',
            name='node_id',
        ),
        migrations.AddField(
            model_name='sdpbinding',
            name='vc_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='port',
            name='node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='services.node'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saps', to='services.port'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saps', to='services.service'),
        ),
        migrations.AlterField(
            model_name='sdp',
            name='from_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spds_from', to='services.node'),
        ),
        migrations.AlterField(
            model_name='sdp',
            name='to_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdps_to', to='services.node'),
        ),
        migrations.AlterField(
            model_name='sdpbinding',
            name='service_id_str',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdp_bindings', to='services.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.node'),
        ),
    ]
