# Generated by Django 4.0 on 2022-01-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_node_id_node_id_rename_sdp_id_sdp_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdpbinding',
            old_name='service_id_str',
            new_name='service',
        ),
    ]
