# Generated by Django 4.0 on 2022-01-10 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_service_id_str_sdpbinding_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdpbinding',
            name='sdp_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='services.sdp'),
            preserve_default=False,
        ),
    ]
