# Generated by Django 4.0 on 2022-01-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_sdpbinding_sdp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sap',
            name='inner_vlan',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sap',
            name='outer_vlan',
            field=models.IntegerField(null=True),
        ),
    ]
